export const OPENAI_API_KEY = "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";

export const PERSONALITIES = [
	"Jésus de Nazareth",
	"Bouddha",
	"Mahatma Gandhi",
	"Jules César",
	"Alexandre le Grand",
	"Confucius",
	"Cléopâtre",
	"Napoléon Bonaparte",
	"William Shakespeare",
	"Martin Luther King Jr.",
	"Winston Churchill",
	"Genghis Khan",
	"Marie Curie",
	"Moïse",
	"Léonard de Vinci",
	"Jeanne d'Arc",
	"Abraham Lincoln",
	"Akbar le Grand",
	"Nelson Mandela",
	"Isaac Newton",
	"Marco Polo",
	"Galilée",
	"Albert Einstein",
	"Vasco de Gama",
	"Rosa Parks",
	"Muhammad Ali",
	"Christopher Colomb",
	"Ramsès II",
	"Ashoka",
	"Laozi",
	"Marie - Antoinette",
	"John F.Kennedy",
	"Aristote",
	"Socrate",
	"John Stuart Mill",
	"Karl Marx",
	"Averroès",
	"Avicenne",
	"Immanuel Kant",
	"Friedrich Nietzsche",
	"Jean - Jacques Rousseau",
	"Thomas Hobbes",
	"Confucius",
	"Søren Kierkegaard",
	"Friedrich Hegel",
	"Simone de Beauvoir",
	"Jean - Paul Sartre",
	"Albert Camus",
	"Mark Zuckerberg",
	"Jeff Bezos",
	"Bill Gates",
	"Elon Musk",
	"Oprah Winfrey",
	"Larry Page",
	"Sergey Brin",
	"Larry Ellison",
	"Richard Branson",
	"Steve Jobs",
	"Jack Ma",
	"Mukesh Ambani",
	"Warren Buffett",
	"Michael Bloomberg",
	"Howard Schultz",
	"Tim Cook",
	"Phil Knight",
	"Michael Dell",
	"Bernard Arnault",
	"Li Ka - shing",
	"Zhang Yiming",
	"Richard Li",
	"Carlos Slim",
	"Oprah Winfrey",
	"George Soros",
	"Ray Kroc",
	"Estée Lauder",
	"Howard Hughes",
	"Amelia Earhart",
	"Thomas Edison",
	"Marie Curie",
	"Nikola Tesla",
	"Sir Isaac Newton",
	"Galileo Galilei",
	"Leonardo da Vinci",
	"Michelangelo",
	"Christopher Columbus",
	"Wolfgang Amadeus Mozart",
	"Ludwig van Beethoven",
	"Charles Darwin",
	"Thomas Jefferson",
	"Karl Marx",
	"Charles Dickens",
	"Alexander Hamilton",
	"Abraham Lincoln",
	"Albert Einstein",
	"Franklin D.Roosevelt",
	"Winston Churchill",
	"Martin Luther King Jr.",
	"Nelson Mandela",
	"Steve Wozniak",
	"Cleisthenes(Athènes, Grèce)",
	"Tutankhamun(Égypte ancienne)",
	"Anne Frank(Pays - Bas)",
	"Henry Ford(États - Unis)",
	"Marie - Antoinette(Autriche / France)",
	"Auguste César(Rome)",
	"Catherine la Grande(Russie)",
	"Harriet Tubman(États - Unis)",
	"Confucius(Chine)",
	"Genghis Khan(Mongolie)",
	"Thomas Jefferson(États - Unis)",
	"James Cook(Royaume - Uni)",
	"Joan Baez(États - Unis)",
	"Charles de Gaulle(France)",
	"Frida Kahlo(Mexique)",
	"Amelia Earhart(États - Unis)",
	"Henry VIII(Angleterre)",
	"William the Conqueror(Normandie)",
	"Alexander Graham Bell(Écosse / Canada)",
	"Sojourner Truth(États - Unis)",
	"Anne Boleyn(Angleterre)",
	"Karl Marx(Allemagne)",
	"Isaac Newton(Angleterre)",
	"Charles Dickens(Angleterre)",
	"George Washington(États - Unis)",
	"Elizabeth I(Angleterre)",
	"Thomas Edison(États - Unis)",
	"Galileo Galilei(Italie)",
	"Nikola Tesla(Serbie / États - Unis)",
	"Thomas Aquinas(Italie)",
	"William Wallace(Écosse)",
	"Andrew Carnegie(Écosse / États - Unis)",
	"Louis XIV(France)",
	"Sun Yat - sen(Chine)",
	"Marcus Aurelius(Rome)",
	"Rumi(Empire seldjoukide)",
	"Hernán Cortés(Espagne)",
	"Johann Sebastian Bach(Allemagne)",
	"Wolfgang Amadeus Mozart(Autriche)",
	"Ludwig van Beethoven(Allemagne)",
	"Florence Nightingale(Royaume - Uni)",
	"Ada Lovelace(Royaume - Uni)",
	"John Locke(Angleterre)",
	"Voltaire(France)",
	"James Madison(États - Unis)",
	"Gaius Julius Caesar(Rome)",
	"John Adams(États - Unis)",
	"Johannes Gutenberg(Allemagne)",
	"Michel de Montaigne(France)",
	"Mary Wollstonecraft(Royaume - Uni)",
	"Emily Dickinson(États - Unis)",
	"Queen Victoria(Royaume - Uni)",
	"Harriet Beecher Stowe(États - Unis)",
	"Sigmund Freud(Autriche)",
	"Albert Schweitzer(France)",
	"Mahatma Gandhi(Inde)",
	"Franklin D.Roosevelt(États - Unis)",
	"Mao Zedong(Chine)",
	"Charles de Gaulle(France)",
	"John F.Kennedy(États - Unis)",
	"Pablo Picasso(Espagne)",
	"Indira Gandhi(Inde)",
	"Salvador Dali(Espagne)",
	"Neil Armstrong(États - Unis)",
	"Martin Luther(Allemagne)",
	"Joseph Staline(Union soviétique)",
	"Ernest Hemingway(États - Unis)",
	"Bob Dylan(États - Unis)",
	"Elvis Presley(États - Unis)",
	"Anne Frank(Pays - Bas)",
	"Che Guevara(Argentine / Cuba)",
	"Alexander Fleming(Royaume - Uni)",
	"Mohandas Karamchand Gandhi(Inde)",
	"Margaret Thatcher(Royaume - Uni)",
	"Angela Merkel(Allemagne)",
	"Mother Teresa(Inde)",
	"Malala Yousafzai(Pakistan)",
	"Eleanor Roosevelt(États - Unis)",
	"Nikola Tesla(Serbie / États - Unis)",
	"Ada Lovelace(Royaume - Uni)",
	"Marie Curie(Pologne / France)",
	"Isaac Newton(Angleterre)",
	"Galileo Galilei(Italie)",
	"Leonardo da Vinci(Italie)",
	"Michel - Ange(Italie"
]

export const CATEGORIES = {
	'Food': [
		"Techniques of cooking(baking, cutting, etc.)",
		"Pastry and baking",
		"International cuisine(specific cuisines)",
		"Culinary art(plating and presentation)",
		"Nutrition and dietetics"
	],
	'Design': [
		"Graphic design(logos, posters, etc.)",
		"Interior design(layout, decoration)",
		"Product design(object, packaging)",
		"Web design(user interface, user experience)",
		"Creative and artistic techniques"
	],
	'Style': [
		"Fashion and personal style tips",
		"Accessories and jewelry(selection and pairing)",
		"Hairstyling and makeup(trends, techniques)",
		"Clothing styles(vintage, modern, etc.)",
		"Image and presentation advice"
	],
	'Arts': [
		"Specific art techniques(watercolor, sculpture, etc.)",
		"Color theory and art composition",
		"Art history and art movements",
		"Digital and multimedia art practices",
		"Exploration of different art materials and mediums"
	],
	'Entertainment': [
		"Film analysis and critiques",
		"Scriptwriting and creative storytelling",
		"Organizing cultural events or performances",
		"Writing and literary critique",
		"Exploring arts and cultural discoveries"
	],
	'Music': [
		"Learning specific instruments(piano, guitar, etc.)",
		"Music composition and arrangement",
		"Vocal techniques and singing",
		"Specific music genres(rock, jazz, classical, etc.)",
		"Music notation and music theory"
	],
	'Business': [
		"Business planning and strategy",
		"Marketing and corporate communication",
		"Human resources management",
		"Accounting and finance for businesses",
		"Entrepreneurship and project development"
	],
	'Sport': [
		"Specific physical training for sports",
		"Rules and techniques for individual or team sports",
		"Mental preparation and motivation in sports",
		"Game analysis and sport tactics",
		"Health and well - being for athletes"
	],
	'Gaming': [
		"Analysis and review of specific games",
		"Skills and strategies for video games",
		"Game content creation(streaming, videos)",
		"Game design and development",
		"Gaming culture and news"
	],
	'Science': [
		"Scientific specializations(biology, physics, etc.)",
		"Scientific research methods",
		"Recent scientific discoveries",
		"Practical applications of science",
		"Exploration of the natural world and universe"
	],
	'Tech': [
		"Programming and software development",
		"Emerging technologies and trends",
		"Cybersecurity and data protection",
		"Use of specific tools and software",
		"Web design and development"
	],
	'Writing': [
		"Creative writing(fiction, poetry, etc.)",
		"Journalism and reporting",
		"Blogging and online writing",
		"Academic and professional writing techniques",
		"Publishing and self - publishing"
	],
	'Home': [
		"DIY and home repairs",
		"Interior decoration and design",
		"Gardening and landscaping",
		"Home organization and storage",
		"Renovation and home improvement projects"
	],
	'LifeStyle': [
		"Stress management and relaxation techniques",
		"Travel and cultural exploration",
		"Leisure and recreational activities",
		"Personal development and well - being",
		"Healthy cooking and balanced nutrition"
	],
	'Community': [
		"Civic engagement and volunteering",
		"Social awareness and humanitarian causes",
		"Organizing community events",
		"Social inclusion and cultural diversity",
		"Communication and conflict resolution"
	],
	'Government': [
		"Political systems and governance",
		"Electoral processes and public policies",
		"International relations and diplomacy",
		"Civil rights and social justice",
		"Civic engagement and activism"
	],
	'Wellness': [
		"Stress management and relaxation",
		"Meditation and mindfulness",
		"Yoga and well - being exercises",
		"Mental and emotional health",
		"Personal development and spiritual growth"
	],
	'AI(Artificial Intelligence)': [
		"Machine learning algorithms",
		"Neural networks and deep learning",
		"Natural language processing(NLP)",
		"Computer vision and image recognition",
		"AI ethics and responsible AI"
	]
}